export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SHOW_ALERT = 'SHOW_ALERT';
